#include "color_map/color.hh"
#include <fstream>
#include <iostream>
#include <ppm_writer/ppm_writer.hh>

nucray::ppm_writer::ppm_writer() : width(0), height(0) {
}

void nucray::ppm_writer::set_pixels(size_t width,
                                    size_t height,
                                    std::vector<nucray::color> pixels) {
        this->width = width;
        this->height = height;
        this->pixels = pixels;
}

void nucray::ppm_writer::write(std::string filename) {
        std::ofstream file(filename.c_str());
        file << "P6\n";
        file << "# Image generated by nuclear_raytracer       \n";
        file << this->width << " " << this->height << "\n";
        file << "255\n";
        std::cout << sizeof(nucray::color) << " " << pixels.size() << " "
                  << this->width << " " << this->height << std::endl;
        size_t byte_size = this->width*this->height*3;
        char *data_to_write = new char[byte_size];
        size_t data_index = 0;
        for (auto &c : this->pixels) {
                data_to_write[data_index++] = c.color_channals.red;
                data_to_write[data_index++] = c.color_channals.green;
                data_to_write[data_index++] = c.color_channals.blue;
        }
        file.write(data_to_write,
                   byte_size);
        file.close();
        delete [] data_to_write;
}
